---
env:
  global:
    - secure:
      - "sD46YBkS4HzQGp4LooNSIkTLYwRapHtDTUvwuokuNH1ZQsQvBgm2Q6AO1hOWCm17gan8o0WlR8FWs58U7US9yfZQHHAwKN+R4tL/m0S7S/AlvvIaWTxbR27+jn2eP3kKbnJRnsMmAdEfcP8SyxLORcJB9jFFIdA7YGyH22JO4LChrF7vJb5ZJALVw2817aAG6hGMyRHRcUSCWUZ8pPcmnmsjmcQ9PiSOokMtBW/Q5Mt3KaKUDDHyAn4N/idiJIKfE4i3NaYfAEYgHY1rV5hqLZNcqk2YLwG0FaZ2N8U5hSGNC/SMvir9G7v6L/IEa2gWOBJxyWz+a0CSmZ1wtnfT9QjWZGotq7Wvv6kQSQ89jFnvdl0nGzs2Q/7pn6z/HUotX0zgdhjAdr8SG7wtEiye00kZSPB2T9SKhza55S2CEsBLAFcaV8X2+0YW7rTa6CBWCCv7Uqw3VwtMFfbWpjVkgB/afP0cVYcod5DUGLcTJ0ynRPqscB+nNjFce3WKR5IhRySHeLFK9dVPG90spaMK++tvXczBj4EFMkd/cTQ6jqPjMdV8xnaTLcRHhtBjbQj2XkB234PpHEN2YFHKmyI7Xj4ug3BPuUs03dl/qAZJPNvNUZxIYdku/SzFuNR/rGAceVcz1qzzqr//PnQwK9Dm2J/W5grpjzNZNLBmU5ztRG4="

language: ruby
cache: bundler
rvm:
  - 2.6.1
before_install: gem install bundler -v '<2'
